# Emoji Sentiment

Are popular emojis generally associated with positive or negative sentiments?

The file `"emoji-sentiment.csv"` provides data on the sentiment associated with various emojis.

Researchers examined 1.6 million tweets across 13 European languages. Each tweet was labeled by annotators as positive (+1), negative (-1), or neutral (0). About 4% of these tweets included emojis.

Columns include:
- `Occurrences [5...max]`: Number of times the emoji appears in the dataset.
- `Position [0...1]`: Average position of the emoji in tweets, from start (0) to end (1).
- `Neg [0...1]`: Percentage of tweets with the emoji that are 'negative'.
- `Neu [0...1]`: Percentage of tweets with the emoji that are 'neutral'.
- `Pos [0...1]`: Percentage of tweets with the emoji that are 'positive'.

In [107]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'emoji-sentiment.csv'.

# from google.colab import files
# uploaded = files.upload()

In [108]:
import pandas as pd
df = pd.read_csv('emoji-sentiment.csv')
df.head(3)

,Char,Image [twemoji],Unicode codepoint,Occurrences [5...max],Position [0...1],Neg [0...1],Neut [0...1],Pos [0...1],Sentiment bar (c.i. 95%),Unicode name,Unicode block
0,😂,😂,0x1f602,14622,0.805,0.247,0.285,0.468,NaN,FACE WITH TEARS OF JOY,Emoticons
1,❤,❤,0x2764,8050,0.747,0.044,0.166,0.790,NaN,HEAVY BLACK HEART,Dingbats
2,♥,♥,0x2665,7144,0.754,0.035,0.272,0.693,NaN,BLACK HEART SUIT,Miscellaneous Symbols

### Project Ideas:

Data Cleaning: 
- Remove unnecessary columns that are not useful for your analysis.

- Rename the remaining columns using `snake_case` (all lowercase letters with underscores between words).

New Variables:
- Add a new column called `sentiment`, where sentiment = (% positive tweets) - (% negative tweets).

- Add a `positive_flag` column that is `True` if `sentiment > 0` (or above a set threshold), otherwise `False`.

Types of questions you can now answer more easily:
- What percentage of emojis in the dataset have a positive sentiment?

- What percentage of the top 20 most popular emojis are positive?

- Which emoji (with more than 500 mentions) is the most positive?

- Which emoji (with more than 500 mentions) is the most negative?

- Where in the tweets are most emojis located (i.e. at the beginning or the end)?

- Is there a difference in the placement of positive versus negative emojis within a tweet?

In [109]:
df = df.drop(columns=['Image [twemoji]', 'Unicode codepoint', 'Sentiment bar (c.i. 95%)', 'Unicode name', 'Unicode block'])

name_map = {
    'Char' : 'char',
    'Occurrences [5...max]' : 'occurrences',
    'Position [0...1]' : 'position',
    'Neg [0...1]' : 'neg',
    'Neut [0...1]' : 'neut', 
    'Pos [0...1]' : 'pos'
}
df = df.rename(columns=name_map)

df

    char  occurrences  position    neg   neut    pos
0      😂        14622     0.805  0.247  0.285  0.468
1      ❤         8050     0.747  0.044  0.166  0.790
2      ♥         7144     0.754  0.035  0.272  0.693
3      😍         6359     0.765  0.052  0.219  0.729
4      😭         5526     0.803  0.436  0.220  0.343
..   ...          ...       ...    ...    ...    ...
746    ♮            5     0.937  0.125  0.625  0.250
747    🅾            5     0.977  0.375  0.375  0.250
748    🔄            5     0.971  0.125  0.750  0.125
749    ☄            5     0.435  0.125  0.750  0.125
750    ☨            5     0.458  0.125  0.750  0.125

[751 rows x 6 columns]

In [110]:
df['sentiment'] = df['pos'] - df['neg']
df['positive_flag'] = df['sentiment'] > 0
df

    char  occurrences  position    neg   neut    pos  sentiment  positive_flag
0      😂        14622     0.805  0.247  0.285  0.468      0.221           True
1      ❤         8050     0.747  0.044  0.166  0.790      0.746           True
2      ♥         7144     0.754  0.035  0.272  0.693      0.658           True
3      😍         6359     0.765  0.052  0.219  0.729      0.677           True
4      😭         5526     0.803  0.436  0.220  0.343     -0.093          False
..   ...          ...       ...    ...    ...    ...        ...            ...
746    ♮            5     0.937  0.125  0.625  0.250      0.125           True
747    🅾            5     0.977  0.375  0.375  0.250     -0.125          False
748    🔄            5     0.971  0.125  0.750  0.125      0.000          False
749    ☄            5     0.435  0.125  0.750  0.125      0.000          False
750    ☨            5     0.458  0.125  0.750  0.125      0.000          False

[751 rows x 8 columns]

In [111]:
pos_percentage = df['positive_flag'].mean() * 100
print(f'Percentage of positive sentiments: {pos_percentage:.2f}%')

Percentage of positive sentiments: 82.42%

In [112]:
popular = df.sort_values(by='occurrences', ascending=False).head(20)
pos_pop_percentage = popular['positive_flag'].mean() * 100

print(popular)
print(f'Percentage of positive sentiments in top 20 most popular emojis: {pos_pop_percentage:.2f}%')

   char  occurrences  position    neg   neut    pos  sentiment  positive_flag
0     😂        14622     0.805  0.247  0.285  0.468      0.221           True
1     ❤         8050     0.747  0.044  0.166  0.790      0.746           True
2     ♥         7144     0.754  0.035  0.272  0.693      0.658           True
3     😍         6359     0.765  0.052  0.219  0.729      0.677           True
4     😭         5526     0.803  0.436  0.220  0.343     -0.093          False
5     😘         3648     0.854  0.053  0.193  0.754      0.701           True
6     😊         3186     0.813  0.060  0.237  0.704      0.644           True
7     👌         2925     0.805  0.094  0.249  0.657      0.563           True
8     💕         2400     0.766  0.042  0.285  0.674      0.632           True
9     👏         2336     0.787  0.104  0.271  0.624      0.520           True
10    😁         2189     0.796  0.127  0.296  0.577      0.450           True
11    ☺         2062     0.799  0.062  0.218  0.720      0.658           True
12    ♡         1975     0.764  0.052  0.227  0.721      0.669           True
13    👍         1854     0.812  0.115  0.248  0.637      0.522           True
14    😩         1808     0.826  0.591  0.186  0.223     -0.368          False
15    🙏         1539     0.794  0.081  0.421  0.498      0.417           True
16    ✌         1534     0.790  0.113  0.310  0.576      0.463           True
17    😏         1522     0.765  0.112  0.444  0.444      0.332           True
18    😉         1521     0.845  0.100  0.337  0.563      0.463           True
19    🙌         1506     0.791  0.101  0.238  0.661      0.560           True
Percentage of positive sentiments in top 20 most popular emojis: 90.00%

In [ ]:
occ_500 = df.query('occurrences > 500')
most_pos_sentiment = occ_500.sort_values(by='sentiment', ascending=False)

print(most_pos_sentiment.head(10))
print(f'Most positive emoji (with more than 500 mentions): {most_pos_sentiment.head(1)['char']}')

   char  occurrences  position    neg   neut    pos  sentiment  positive_flag
1     ❤         8050     0.747  0.044  0.166  0.790      0.746           True
49    💞          687     0.829  0.041  0.180  0.780      0.739           True
29    🎉         1125     0.744  0.039  0.184  0.777      0.738           True
24    💃         1344     0.853  0.045  0.177  0.779      0.734           True
34    💙          912     0.703  0.033  0.204  0.763      0.730           True
25    💖         1263     0.762  0.043  0.201  0.755      0.712           True
54    💛          602     0.752  0.043  0.205  0.752      0.709           True
5     😘         3648     0.854  0.053  0.193  0.754      0.701           True
44    💋          734     0.801  0.039  0.231  0.730      0.691           True
3     😍         6359     0.765  0.052  0.219  0.729      0.677           True
Most positive emoji (with more than 500 mentions): 1    ❤
Name: char, dtype: object

In [117]:
most_neg_sentiment = occ_500.sort_values(by='sentiment', ascending=True)

print(most_neg_sentiment.head(10))
print(f'Most negative emoji (with more than 500 mentions): {most_neg_sentiment.head(1)['char']}')

   char  occurrences  position    neg   neut    pos  sentiment  positive_flag
23    😒         1385     0.858  0.591  0.192  0.217     -0.374          False
14    😩         1808     0.826  0.591  0.186  0.223     -0.368          False
53    🔫          604     0.894  0.493  0.209  0.298     -0.195          False
41    😡          756     0.862  0.532  0.108  0.360     -0.172          False
27    😔         1205     0.866  0.464  0.219  0.318     -0.146          False
58    😞          532     0.825  0.479  0.161  0.361     -0.118          False
4     😭         5526     0.803  0.436  0.220  0.343     -0.093          False
47    😴          718     0.850  0.422  0.237  0.341     -0.081          False
39    █          798     0.634  0.090  0.853  0.057     -0.033          False
31    ☯          992     0.384  0.006  0.987  0.007      0.001           True
Most negative emoji (with more than 500 mentions): 23    😒
Name: char, dtype: object

In [118]:
most_loc = df['position'].value_counts().reset_index()

print(most_loc)
print(f'Location where most emojis located at: {most_loc.head(1)['position']}')

     position  count
0       0.739      8
1       0.794      6
2       0.840      5
3       0.604      5
4       0.786      5
..        ...    ...
420     0.034      1
421     0.501      1
422     0.740      1
423     0.287      1
424     0.435      1

[425 rows x 2 columns]
Location where most emojis located at: 0    0.739
Name: position, dtype: float64

In [119]:
pos_avg_loc = df.query('positive_flag == True')['position'].mean()
neg_avg_loc = df.query('positive_flag == False')['position'].mean()

print(f'Difference in the placement of positive versus negative emojis: {neg_avg_loc:.2f} - {pos_avg_loc:.2f} = {(neg_avg_loc - pos_avg_loc):.4f}')

Difference in the placement of positive versus negative emojis: 0.68 - 0.66 = 0.0188