# Volcano Eruptions

Which volcanoes have experienced the longest eruptions?

The dataset `volcanic-eruptions.csv` includes the start and end dates for all volcanic eruptions since 1800, along with each volcano's identification number. For eruptions that are still ongoing as of December 2024, the end date is recorded as December 2024.

This dataset excludes any eruptive pauses shorter than three months. If an eruption resumes after more than three months of inactivity, it is classified as a new eruption.

Note: Volcano Yasur in Vanuatu is not included in this list due to the absence of a clear start date.

In [67]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'volcanic-eruptions.csv' and 'volcano-list.csv'.

# from google.colab import files
# uploaded = files.upload()

In [68]:
import pandas as pd
import matplotlib.pyplot as plt

eruptions = pd.read_csv('volcanic-eruptions.csv')
eruptions.head(3)

   volcano_id start_date end_date
0      211020    07-1913  04-1944
1      211020    02-1864  11-1868
2      211020    12-1854  05-1855

### Additional dataset

The dataset `volcano-list.csv` provides detailed information about each volcano, including its name, country, latitude, longitude, and type.

In [69]:
volcanoes = pd.read_csv('volcano-list.csv')
volcanoes.head(3)

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type
0,210010,West Eifel Volcanic Field,Germany,European Volcanic Regions,Central European Volcanic Province,Cluster,Volcanic field,Eruption Dated,8300 BCE,50.170,6.850,600,Rift zone / Continental crust (>25 km),Foidite
1,210020,Chaine des Puys,France,European Volcanic Regions,Western European Volcanic Province,Cluster,Lava dome(s),Eruption Dated,4040 BCE,45.786,2.981,1464,Rift zone / Continental crust (>25 km),Basalt / Picro-Basalt
2,210030,Olot Volcanic Field,Spain,European Volcanic Regions,Western European Volcanic Province,Cluster,Volcanic field,Evidence Credible,Unknown,42.170,2.530,893,Intraplate / Continental crust (>25 km),Trachybasalt / Tephrite Basanite

### Project Ideas:

- Find the volcanoes that were erupting as of Dec 2024.

- Find the volcanoes that have had the longest volcanic eruptions. 

Hints:
- Use `pd.to_datetime`.

- Merge the volcanoes dataframe into eruptions.

- Before the merge, reduce the dataframes to the columns of interest.

- Use `df.sort_values`.

In [70]:
volcano_eruptions = pd.merge(volcanoes, eruptions, on='volcano_id', how='left').dropna()
volcano_eruptions

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type,start_date,end_date
6,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,14.426,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,07-1913,04-1944
7,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,14.426,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,02-1864,11-1868
8,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,14.426,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,12-1854,05-1855
9,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,14.426,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,12-1855,12-1861
10,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,14.426,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,07-1824,09-1834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4569,390090,Saunders,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-57.800,-26.483,843,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,01-1999,01-1999
4570,390090,Saunders,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-57.800,-26.483,843,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,11-2014,10-2024
4571,390090,Saunders,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-57.800,-26.483,843,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,04-1995,02-1998
4575,390130,Zavodovski,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2016 CE,-56.300,-27.570,551,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,03-2016,06-2016
4576,390140,Protector Seamounts,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Cluster,Volcanic field,Eruption Observed,1962 CE,-55.912,-28.167,-55,Subduction zone / Oceanic crust (< 15 km),Rhyolite,03-1962,03-1962

In [71]:
dec_2024_volcano = volcano_eruptions[volcano_eruptions['end_date'] == '12-2024']
display(dec_2024_volcano)
print(dec_2024_volcano.shape[0])

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type,start_date,end_date
20,211040,Stromboli,Italy,European Volcanic Regions,Aeolian Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,38.7890,15.2130,924,Subduction zone / Continental crust (>25 km),Trachyandesite / Basaltic Trachyandesite,02-1934,12-2024
35,211060,Etna,Italy,European Volcanic Regions,Sicily Volcanic Province,Composite,Stratovolcano(es),Eruption Observed,2024 CE,37.7480,14.9990,3357,Subduction zone / Continental crust (>25 km),Trachybasalt / Tephrite Basanite,11-2022,12-2024
130,221080,Erta Ale,Ethiopia,Eastern Africa Volcanic Regions,Afar Rift Volcanic Province,Shield,Shield,Eruption Observed,2024 CE,13.6010,40.6660,585,Rift zone / Intermediate crust (15-25 km),Basalt / Picro-Basalt,07-1967,12-2024
208,222120,"Lengai, Ol Doinyo",Tanzania,Eastern Africa Volcanic Regions,Kenyan Rift Volcanic Province,Composite,Stratovolcano,Eruption Observed,2024 CE,-2.7640,35.9140,2962,Rift zone / Continental crust (>25 km),Foidite,04-2017,12-2024
241,223020,Nyamulagira,DR Congo,Eastern Africa Volcanic Regions,Albertine Rift Volcanic Province,Shield,Shield,Eruption Observed,2024 CE,-1.4080,29.2000,3058,Rift zone / Continental crust (>25 km),Trachybasalt / Tephrite Basanite,04-2018,12-2024
473,234010,Heard,Australia,Somalian-Antarctic Volcanic Regions,Kerguelen Hotspot Volcano Group,Composite,Stratovolcano,Eruption Observed,2024 CE,-53.1060,73.5130,2745,Intraplate / Oceanic crust (< 15 km),Trachybasalt / Tephrite Basanite,09-2012,12-2024
499,241040,Whakaari/White Island,New Zealand,Tonga-Kermadec Volcanic Regions,Taupo Volcanic Zone,Composite,Stratovolcano(es),Eruption Observed,2024 CE,-37.5200,177.1800,294,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,05-2024,12-2024
663,243060,Tofua,Tonga,Tonga-Kermadec Volcanic Regions,Tofua Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,-19.7500,-175.0700,515,Subduction zone / Oceanic crust (< 15 km),Andesite / Basaltic Andesite,10-2015,12-2024
675,243080,Home Reef,Tonga,Tonga-Kermadec Volcanic Regions,Tofua Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-18.9920,-174.7750,-10,Subduction zone / Oceanic crust (< 15 km),Dacite,12-2024,12-2024
739,251020,Manam,Papua New Guinea,Southwest Pacific Volcanic Regions,Bismarck Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-4.0800,145.0370,1807,Subduction zone / Continental crust (>25 km),Basalt / Picro-Basalt,05-2018,12-2024
762,252010,Langila,Papua New Guinea,Southwest Pacific Volcanic Regions,Bismarck Volcanic Arc,Composite,Complex,Eruption Observed,2024 CE,-5.5250,148.4200,1330,Subduction zone / Continental crust (>25 km),Basalt / Picro-Basalt,10-2015,12-2024
916,256010,Tinakula,Solomon Islands,Southwest Pacific Volcanic Regions,Vanuatu Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-10.3860,165.8040,796,Subduction zone / Crustal thickness unknown,Andesite / Basaltic Andesite,12-2018,12-2024
1078,261140,Marapi,Indonesia,Sunda-Banda Volcanic Regions,Sunda Volcanic Arc,Composite,Complex,Eruption Observed,2024 CE,-0.3800,100.4740,2885,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,12-2023,12-2024
1368,263250,Merapi,Indonesia,Sunda-Banda Volcanic Regions,Sunda Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-7.5400,110.4460,2910,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,12-2020,12-2024
1414,263300,Semeru,Indonesia,Sunda-Banda Volcanic Regions,Sunda Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-8.1080,112.9220,3657,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,06-2017,12-2024
1544,263340,Raung,Indonesia,Sunda-Banda Volcanic Regions,Sunda Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-8.1190,114.0560,3260,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,12-2024,12-2024
1645,264180,Lewotobi,Indonesia,Sunda-Banda Volcanic Regions,Sunda Volcanic Arc,Composite,Stratovolcano(es),Eruption Observed,2024 CE,-8.5420,122.7750,1703,Subduction zone / Crustal thickness unknown,Andesite / Basaltic Andesite,12-2023,12-2024
1836,268010,Dukono,Indonesia,Western Pacific Volcanic Regions,Halmahera Volcanic Arc,Composite,Complex,Eruption Observed,2024 CE,1.6992,127.8783,1273,Subduction zone / Oceanic crust (< 15 km),Andesite / Basaltic Andesite,08-1933,12-2024
1840,268030,Ibu,Indonesia,Western Pacific Volcanic Regions,Halmahera Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,1.4880,127.6300,1325,Subduction zone / Oceanic crust (< 15 km),Andesite / Basaltic Andesite,04-2008,12-2024
1940,272020,Kanlaon,Philippines,Western Pacific Volcanic Regions,Negros-Sulu Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,10.4096,123.1300,2422,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,10-2024,12-2024
2014,273070,Taal,Philippines,Western Pacific Volcanic Regions,Taiwan-Luzon Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,14.0106,120.9975,311,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,04-2024,12-2024
2069,282030,Suwanosejima,Japan,Western Pacific Volcanic Regions,Ryukyu Volcanic Arc,Composite,Stratovolcano(es),Eruption Observed,2024 CE,29.6380,129.7140,796,Subduction zone / Oceanic crust (< 15 km),Andesite / Basaltic Andesite,10-2004,12-2024
2114,282080,Aira,Japan,Western Pacific Volcanic Regions,Ryukyu Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,31.5772,130.6589,1117,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,03-2017,12-2024
2520,284141,Ahyi,United States,Northwest Pacific Volcanic Regions,Mariana Volcanic Arc,Composite,Stratovolcano,Eruption Dated,2024 CE,20.4200,145.0300,-75,Subduction zone / Crustal thickness unknown,Andesite / Basaltic Andesite,08-2024,12-2024
2750,290380,Ebeko,Russia,Northwest Pacific Volcanic Regions,Kuril Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,50.6860,156.0140,1103,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,06-2022,12-2024
2834,300130,Karymsky,Russia,Northwest Pacific Volcanic Regions,Eastern Kamchatka Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,54.0490,159.4430,1513,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,06-2024,12-2024
2990,300270,Sheveluch,Russia,Northwest Pacific Volcanic Regions,Eastern Kamchatka Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,56.6530,161.3600,3283,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,08-1999,12-2024
3065,311120,Great Sitkin,United States,North America Volcanic Regions,Aleutian Ridge Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,52.0760,-176.1300,1740,Subduction zone / Intermediate crust (15-25 km),Andesite / Basaltic Andesite,05-2021,12-2024
3379,332010,Kilauea,United States,Eastern Pacific Volcanic Regions,Hawaiian-Emperor Hotspot Volcano Group,Shield,Shield,Eruption Observed,2024 CE,19.4210,-155.2870,1222,Intraplate / Oceanic crust (< 15 km),Basalt / Picro-Basalt,12-2024,12-2024
3534,341090,Popocatepetl,Mexico,Middle America-Caribbean Volcanic Regions,Trans-Mexican Volcanic Belt,Composite,Stratovolcano(es),Eruption Observed,2024 CE,19.0230,-98.6220,5393,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,01-2005,12-2024
3558,342030,Santa Maria,Guatemala,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,14.7570,-91.5520,3745,Subduction zone / Continental crust (>25 km),Dacite,06-1922,12-2024
3573,342090,Fuego,Guatemala,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Composite,Stratovolcano(es),Eruption Observed,2024 CE,14.4730,-90.8800,3763,Subduction zone / Continental crust (>25 km),Basalt / Picro-Basalt,01-2002,12-2024
3791,344100,Masaya,Nicaragua,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,11.9844,-86.1688,594,Subduction zone / Continental crust (>25 km),Basalt / Picro-Basalt,10-2015,12-2024
3845,345020,Rincon de la Vieja,Costa Rica,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Composite,Complex,Eruption Observed,2024 CE,10.8300,-85.3240,1916,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,06-2021,12-2024
3937,351020,"Ruiz, Nevado del",Colombia,South America Volcanic Regions,Northern Andean Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,4.8920,-75.3240,5279,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,11-2014,12-2024
3988,352010,Reventador,Ecuador,South America Volcanic Regions,Northern Andean Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-0.0770,-77.6560,3562,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,07-2008,12-2024
4046,352090,Sangay,Ecuador,South America Volcanic Regions,Northern Andean Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-2.0050,-78.3410,5286,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,03-2019,12-2024
4112,354006,Sabancaya,Peru,South America Volcanic Regions,Central Andean Volcanic Arc,Composite,Stratovolcano(es),Eruption Observed,2024 CE,-15.7870,-71.8570,5960,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,11-2016,12-2024
4327,357120,Villarrica,Chile,South America Volcanic Regions,Southern Andean Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-39.4200,-71.9300,2847,Subduction zone / Continental crust (>25 km),Basalt / Picro-Basalt,12-2014,12-2024
4430,371020,Reykjanes,Iceland,Atlantic Ocean Volcanic Regions,Iceland Neovolcanic Rift Volcanic Province,Cluster,Crater rows,Eruption Observed,2024 CE,63.8170,-22.7170,140,Rift zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,12-2023,12-2024
4549,390020,Erebus,Antarctica,Antarctic-Scotia Volcanic Regions,McMurdo Volcanic Province,Composite,Stratovolcano,Eruption Observed,2024 CE,-77.5300,167.1700,3794,Intraplate / Continental crust (>25 km),Phonolite,12-1972,12-2024

41

In [72]:
volcano_eruptions[['start_month', 'start_year']] = volcano_eruptions['start_date'].str.split('-', expand=True).astype(dtype='int')
volcano_eruptions[['end_month', 'end_year']] = volcano_eruptions['end_date'].str.split('-', expand=True).astype(dtype='int')
volcano_eruptions['duration_months'] = (volcano_eruptions['end_year'] - volcano_eruptions['start_year']) * 12 + (volcano_eruptions['end_month'] - volcano_eruptions['start_month'])

volcano_eruptions

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,...,elevation_m,tectonic_setting,dominant_rock_type,start_date,end_date,start_month,start_year,end_month,end_year,duration_months
6,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,...,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,07-1913,04-1944,7,1913,4,1944,369
7,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,...,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,02-1864,11-1868,2,1864,11,1868,57
8,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,...,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,12-1854,05-1855,12,1854,5,1855,5
9,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,...,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,12-1855,12-1861,12,1855,12,1861,72
10,211020,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.821,...,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite,07-1824,09-1834,7,1824,9,1834,122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4569,390090,Saunders,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-57.800,...,843,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,01-1999,01-1999,1,1999,1,1999,0
4570,390090,Saunders,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-57.800,...,843,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,11-2014,10-2024,11,2014,10,2024,119
4571,390090,Saunders,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-57.800,...,843,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,04-1995,02-1998,4,1995,2,1998,34
4575,390130,Zavodovski,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2016 CE,-56.300,...,551,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt,03-2016,06-2016,3,2016,6,2016,3
4576,390140,Protector Seamounts,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Cluster,Volcanic field,Eruption Observed,1962 CE,-55.912,...,-55,Subduction zone / Oceanic crust (< 15 km),Rhyolite,03-1962,03-1962,3,1962,3,1962,0

In [77]:
volcano_eruptions_sorted = volcano_eruptions.sort_values(by='duration_months', ascending=False)

volcano_eruptions_sorted

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,...,elevation_m,tectonic_setting,dominant_rock_type,start_date,end_date,start_month,start_year,end_month,end_year,duration_months
3558,342030,Santa Maria,Guatemala,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,14.7570,...,3745,Subduction zone / Continental crust (>25 km),Dacite,06-1922,12-2024,6,1922,12,2024,1230
1836,268010,Dukono,Indonesia,Western Pacific Volcanic Regions,Halmahera Volcanic Arc,Composite,Complex,Eruption Observed,2024 CE,1.6992,...,1273,Subduction zone / Oceanic crust (< 15 km),Andesite / Basaltic Andesite,08-1933,12-2024,8,1933,12,2024,1096
20,211040,Stromboli,Italy,European Volcanic Regions,Aeolian Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,38.7890,...,924,Subduction zone / Continental crust (>25 km),Trachyandesite / Basaltic Trachyandesite,02-1934,12-2024,2,1934,12,2024,1090
4049,352090,Sangay,Ecuador,South America Volcanic Regions,Northern Andean Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,-2.0050,...,5286,Subduction zone / Continental crust (>25 km),Andesite / Basaltic Andesite,08-1934,03-2011,8,1934,3,2011,919
3370,332010,Kilauea,United States,Eastern Pacific Volcanic Regions,Hawaiian-Emperor Hotspot Volcano Group,Shield,Shield,Eruption Observed,2024 CE,19.4210,...,1222,Intraplate / Oceanic crust (< 15 km),Basalt / Picro-Basalt,02-1823,12-1894,2,1823,12,1894,862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2479,284120,Ioto,Japan,Northwest Pacific Volcanic Regions,Ogasawara Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,24.7510,...,169,Subduction zone / Crustal thickness unknown,Trachyandesite / Basaltic Trachyandesite,08-2015,08-2015,8,2015,8,2015,0
2477,284120,Ioto,Japan,Northwest Pacific Volcanic Regions,Ogasawara Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,24.7510,...,169,Subduction zone / Crustal thickness unknown,Trachyandesite / Basaltic Trachyandesite,03-1980,03-1980,3,1980,3,1980,0
2475,284120,Ioto,Japan,Northwest Pacific Volcanic Regions,Ogasawara Volcanic Arc,Caldera,Caldera,Eruption Observed,2024 CE,24.7510,...,169,Subduction zone / Crustal thickness unknown,Trachyandesite / Basaltic Trachyandesite,03-1957,03-1957,3,1957,3,1957,0
2473,284110,Kita-Ioto,Japan,Northwest Pacific Volcanic Regions,Ogasawara Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2022 CE,25.4240,...,792,Subduction zone / Crustal thickness unknown,Basalt / Picro-Basalt,03-2022,03-2022,3,2022,3,2022,0
4576,390140,Protector Seamounts,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Cluster,Volcanic field,Eruption Observed,1962 CE,-55.9120,...,-55,Subduction zone / Oceanic crust (< 15 km),Rhyolite,03-1962,03-1962,3,1962,3,1962,0